apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-app
  namespace: mon-zabbix

data:
  MYSQL_DATABASE: zabbix
  MYSQL_USER: zabbix
  ZBX_ENABLE_SNMP_TRAPS: "true"
  ZBX_JAVAGATEWAY_ENABLE: "true"
  ZBX_STARTJAVAPOLLERS: "5"
  ZBX_SERVER_NAME: Composed installation
  ZBX_SERVER_HOST: "zabbix-server"
  ZBX_SERVER_PORT: "10051"
  DB_SERVER_HOST: "10.64.10.82"
  PHP_TZ: "America/Denver"
  ZBX_HOSTNAME: "Zabbix server"
  ZBX_DEBUGLEVEL: "4"
